webapp/account/urls.py
from django.conf.urls import patterns, url, include
from django.contrib.auth.views import password_reset, \
    password_change_done, password_reset_done, \
    password_reset_confirm, password_reset_complete, password_change

from webapp.account.forms import LoginForm, \
    CustomRegistrationForm, CustomPasswordResetForm, \
    CustomPasswordChangeForm, CustomSetPasswordForm
from webapp.account.views import CustomRegistrationView


urlpatterns = patterns('',
    url(r'^login/$',
        'django.contrib.auth.views.login',
        {'authentication_form': LoginForm},
        name='login'),
    url(r'^logout/$',
        'django.contrib.auth.views.logout',
        {'next_page': '/'},
        name='logout'),
    url(r'^password/change/$', password_change,
        {'password_change_form' : CustomPasswordChangeForm},
        name='password_change'),
    url(r'^password/change/done/$', password_change_done),
    url(r'^password/reset/$', password_reset,
        {'password_reset_form' : CustomPasswordResetForm,
         'post_reset_redirect' : '/account/password/reset/done/'},
        name='password_reset'),
    url(r'^password/reset/done/$', password_reset_done),
    url(r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
        password_reset_confirm,
        {'set_password_form' : CustomSetPasswordForm,
         'post_reset_redirect' : '/account/password/done/'},
        name='password_confirm'),
    url(r'^password/done/$', password_reset_complete),
    url(r'^profile/$', 'webapp.account.views.profile', name='edit_profile'),
    url(r'^profile/picture/$', 'webapp.account.views.profile_picture', name='profile_picture'),
    url(r'^register/$',
        CustomRegistrationView.as_view(
            form_class=CustomRegistrationForm,
            success_url='/'),
        name='register'),

    url(r'', include('registration.backends.simple.urls')),
)

webapp/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()


urlpatterns = patterns('',
    url(r'^$', 'webapp.unsigned.views.index', name='index'),
    url(r'^about-us/$', 'webapp.unsigned.views.about', name='about'),
    url(r'^account/', include('webapp.account.urls')),
    url(r'^contact-us/$', 'webapp.unsigned.views.contact', name='contact'),
    url(r'^home/$', 'webapp.home.views.index', name='home'),
    url(r'^privacy-policy/$', 'webapp.unsigned.views.privacy', name='privacy'),
    url(r'^quiver/(?P<quiver_id>\d+)/$', 'webapp.quiver.views.show', name='quiver_show'),
    url(r'^surfboard/(?P<surfboard_id>\d+)/$', 'webapp.surfboard.views.show', name='surfboard_show'),
    url(r'^surfboard/add/$', 'webapp.surfboard.views.add', name='surfboard_add'),
    url(r'^surfboard/delete/(?P<surfboard_id>\d+)/$', 'webapp.surfboard.views.delete', name='surfboard_delete'),
    url(r'^surfboard/edit/(?P<surfboard_id>\d+)/$', 'webapp.surfboard.views.edit', name='surfboard_edit'),
    url(r'^terms-of-service/$', 'webapp.unsigned.views.terms', name='terms'),
)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/surfboard/forms.py
from django import forms
from django.forms import ModelForm
from django.forms.models import inlineformset_factory

from myquivers.models import Surfboard, SurfboardImage


class SurfboardForm(ModelForm):
    class Meta:
        model = Surfboard

    def __init__(self, *args, **kwargs):
        super(SurfboardForm, self).__init__(*args, **kwargs)
        for key, field in self.fields.items():
            if isinstance(field.widget, forms.TextInput) or \
                isinstance(field.widget, forms.Textarea) or \
                isinstance(field.widget, forms.DateInput) or \
                isinstance(field.widget, forms.DateTimeInput) or \
                isinstance(field.widget, forms.Select) or \
                isinstance(field.widget, forms.TimeInput):
                field.widget.attrs.update({'placeholder': field.label,
                                           'class': 'form-control input-xlarge'})

SurfboardImageFormset = inlineformset_factory(Surfboard,
                                              SurfboardImage,
                                              fields=('image',),
                                              can_delete=True,
                                              extra=4,
                                              max_num=4)

webapp/unsigned/forms.py
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(
        max_length=100,
        widget=forms.TextInput(
            attrs={'class': 'form-control',
                   'placeholder': 'Tell us why you are contacting us'}
        )
    )
    message = forms.CharField(
        widget=forms.Textarea(
            attrs={'class': 'form-control',
                   'placeholder': 'Message'}
        )
    )
    sender = forms.EmailField(
        widget=forms.TextInput(
            attrs={'class': 'form-control',
                   'placeholder': 'Please enter your email address'}
        ),
        label='Email'
    )

webapp/account/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response
from django.template import RequestContext

from registration.backends.simple.views import RegistrationView
from webapp.account.forms import ProfileForm


class CustomRegistrationView(RegistrationView):
    def get_success_url(self, request, user):
        # TODO: send welcome email when registration done
        # user.email_user(subject, message, from_email)
        return (settings.LOGIN_REDIRECT_URL, (), {})


def custom_proc(request):
    "A context processor that provides general data."
    return {
        'module': 'account',
    }


@login_required
def profile(request):
    user = request.user

    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, instance=user)
        if profile_form.is_valid():
            profile_form.save()
    else:
        profile_form = ProfileForm(instance=user)

    context = {
        'action': 'profile',
        'form': profile_form
    }

    return render_to_response('account/profile.html', context,
                              context_instance=RequestContext(request, processors=[custom_proc]))

@login_required
def profile_picture(request):
    context = {
        'action': 'profile_picture',
    }

    return render_to_response('account/profile_picture.html', context,
                              context_instance=RequestContext(request, processors=[custom_proc]))

webapp/home/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response
from django.template import RequestContext

from myquivers.models import Quiver


def custom_proc(request):
    "A context processor that provides general data."
    return {
        'module': 'home',
    }


@login_required
def index(request):
    quivers = Quiver.objects.filter(
        user=request.user,
        type='SUR'
    )

    context = {
        'action': 'index',
        'quivers': quivers,
    }

    return render_to_response('home/index.html', context,
                              context_instance=RequestContext(request, processors=[custom_proc]))

webapp/quiver/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext

from myquivers.models import Quiver, Surfboard


def custom_proc(request):
    "A context processor that provides general data."
    return {
        'module': 'quiver',
    }

@login_required
def show(request, quiver_id):
    quiver = get_object_or_404(Quiver, pk=quiver_id)

    if request.user.id != quiver.user.id:
        raise PermissionDenied()

    surfboards = Surfboard.objects.filter(
        quiver__id=quiver_id,
        quiver__user=request.user,
        quiver__type='SUR',
    ).order_by('-id')

    context = {
        'action': 'show',
        'quiver': quiver,
        'surfboards': surfboards
    }

    return render_to_response('quiver/show.html', context,
                              context_instance=RequestContext(request, processors=[custom_proc]))

webapp/surfboard/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext

from myquivers.models import Quiver, Surfboard
from webapp.surfboard.forms import SurfboardForm, SurfboardImageFormset


def custom_proc(request):
    "A context processor that provides general data."
    return {
        'module': 'surfboard',
    }

@login_required
def show(request, surfboard_id):
    surfboard = get_object_or_404(Surfboard, pk=surfboard_id)

    if request.user.id != surfboard.quiver.user.id:
        raise PermissionDenied()

    has_multiple_images = False
    if surfboard.surfboard_images.count() > 1:
        has_multiple_images = True

    context = {
        'action': 'show',
        'surfboard': surfboard,
        'has_multiple_images': has_multiple_images,
    }

    return render_to_response('surfboard/show.html', context,
                              context_instance=RequestContext(request, processors=[custom_proc]))

@login_required
def add(request):
    user = request.user

    image_formset = SurfboardImageFormset(instance=Surfboard())

    if request.method == 'POST':
        surfboard_form = SurfboardForm(request.POST)
        if surfboard_form.is_valid():
            surfboard = surfboard_form.save()
            image_formset = SurfboardImageFormset(
                request.POST,
                request.FILES,
                instance=surfboard
            )
            if image_formset.is_valid():
                image_formset.save()

            return HttpResponseRedirect(reverse('surfboard_show', args=(surfboard.id,)))
    else:
        surfboard_form = SurfboardForm()

    surfboard_form.fields['quiver'].queryset = user.quiver_set.all()
    surfboard_form.fields['quiver'].empty_label = None
    surfboard_form.fields['quiver'].label_from_instance = lambda obj: '%s' % (obj.name)

    context = {
        'action': 'add',
        'form': surfboard_form,
        'image_formset': image_formset
    }

    return render_to_response('surfboard/form.html', context,
                              context_instance=RequestContext(request, processors=[custom_proc]))

@login_required
def edit(request, surfboard_id):
    surfboard = get_object_or_404(Surfboard, pk=surfboard_id)
    user = request.user

    if user.id != surfboard.quiver.user.id:
        raise PermissionDenied()

    surfboard_form = SurfboardForm(instance=surfboard)
    image_formset = SurfboardImageFormset(instance=surfboard)

    surfboard_form.fields['quiver'].queryset = user.quiver_set.all()
    surfboard_form.fields['quiver'].empty_label = None
    surfboard_form.fields['quiver'].label_from_instance = lambda obj: '%s' % (obj.name)

    if request.method == 'POST':
        surfboard_form = SurfboardForm(request.POST, instance=surfboard)
        if surfboard_form.is_valid():
            surfboard = surfboard_form.save(commit=False)
            image_formset = SurfboardImageFormset(
                request.POST,
                request.FILES,
                instance=surfboard
            )
            if image_formset.is_valid():
                surfboard.save()
                image_formset.save()

            return HttpResponseRedirect(reverse('surfboard_show', args=(surfboard.id,)))

    context = {
        'action': 'edit',
        'form': surfboard_form,
        'image_formset': image_formset,
        'surfboard': surfboard
    }

    return render_to_response('surfboard/form.html', context,
                              context_instance=RequestContext(request, processors=[custom_proc]))

@login_required
def delete(request, surfboard_id):
    surfboard = get_object_or_404(Surfboard, pk=surfboard_id)

    if request.user.id != surfboard.quiver.user.id:
        raise PermissionDenied()

    quiver_id = surfboard.quiver_id
    surfboard.delete()

    return HttpResponseRedirect(reverse('quiver_show', args=[quiver_id]))

webapp/unsigned/views.py
from django import forms
from django.conf import settings
from django.contrib.sites.models import Site
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, BadHeaderError
from django.shortcuts import render_to_response
from django.template import RequestContext

from webapp.account.forms import CustomRegistrationForm
from webapp.unsigned.forms import ContactForm


def custom_proc(request):
    "A context processor that provides general data."
    return {
        'module': 'unsigned',
    }

def index(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('home'))

    context = {
        'action': 'index',
        'registration_form': CustomRegistrationForm()
    }

    return render_to_response('unsigned/index.html', context,
                              context_instance=RequestContext(request, processors=[custom_proc]))

def about(request):
    context = {
        'action': 'about',
    }

    return render_to_response('unsigned/about.html', context,
                              context_instance=RequestContext(request, processors=[custom_proc]))

def terms(request):
    context = {
        'action': 'terms',
    }

    return render_to_response('unsigned/terms.html', context,
                              context_instance=RequestContext(request, processors=[custom_proc]))

def privacy(request):
    context = {
        'action': 'privacy',
    }

    return render_to_response('unsigned/privacy.html', context,
                              context_instance=RequestContext(request, processors=[custom_proc]))

def contact(request):
    current_site = Site.objects.get_current()
    confirmation_message = None

    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message'] + \
                      '\r\n\r\nSent via contact form at ' + \
                      current_site.domain + reverse('contact')

            sender = form.cleaned_data['sender']

            try:
                send_mail(subject, message, sender, [settings.DEFAULT_FROM_EMAIL])
                form = ContactForm()
                confirmation_message = 'Your message has been sent. ' \
                                       'We\'ll get back to you as soon as possible.'
            except BadHeaderError:
                errors = form._errors.setdefault(
                    forms.forms.NON_FIELD_ERRORS, forms.util.ErrorList()
                )
                errors.append(
                    'There was an error while trying to '
                    'send the email. Please try again.'
                )
    else:
        form = ContactForm()

    context = {
        'action': 'contact',
        'form': form,
        'confirmation_message': confirmation_message
    }

    return render_to_response('unsigned/contact.html', context,
                              context_instance=RequestContext(request, processors=[custom_proc]))

webapp/templates/unsigned/about.html
{% extends 'layouts/base_layout.html' %}
{% load staticfiles %}

{% block title %}About us - {{ site.name }}{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <h1 class="page-header">About us</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-3">
    {% include "partials/unsigned_side_menu.html" with active='about' %}
  </div>

  <div class="col-md-9">
    <p>MyQuivers.com wants to become a platform for surfbers to manage their surfboards, share them with friends, be able to find reviews and exchange information. It's the easiest way for you to keep track of your old surfboards, your progression, and look for a new surfboard</p>
    <p>Thousands of neighborhoods are already using Nextdoor to build happier, safer places to call home.</p>
    <p>People are using MyQuivers to:</p>

    <ul>
      <li>Remember their old surfboards, especially dimensions but also pictures</li>
      <li>Organize your current boards</li>
      <li>Track down new surfboards you want to buy next</li>
      <li>Find out who surf what around you</li>
      <li>Look for help by asking advices and read reviews</li>
      <li>Finally you'll be able to see your progression/evolution by comparing your old board and current ones</li>
    </ul>

    <p>MyQuivers’s mission is to use the power of technology to build a way to manage surfboards and find your next one.</p>

    <h2 class="page-header">Our mission</h2>
    <p>I created MyQuivers because I believe that there is a lot of things to do to make people find surfboards, sell and trade, and also understand better their surfing abilities by comparing with people surfboard the same spots, the same boards, and for your physical abilities. I hope that surfers everywhere will use the MyQuivers platform to build stronger and better surfer community around the world.</p>
    <p>Based in San Francisco, California, MyQuivers was founded in 2013 and is auto-funded, it is a project that will involve a lot as I really think there are a lot of great things to do to make the surf community better, follow our favorites surfers, understand what they ride, and more. Keep in touch and you'll see improvements every month, new features will be added to make this platform fun and really useful, without making you loose time online and spend less time in the water</p>
    <p>Yep, go surf and have fun! You can also find me somewhere around Ocean Beach in San Francisco, CA (all the way to Santa Cruz), or South West of France when I'm back home, usually between Capbreton and Seignosse.</p>

    <h2 class="page-header">Our team</h2>
    <img class="img-circle img-responsive" src="{% static 'images/team/damien-02.jpg' %}">
    <h3>Damien Poulain <small>Creator</small></h3>
    <p>
      Developed MyQuivers.com as a side project.<br>
      Operations, web development, UX/UI, I did it all.<br>
      <a href="https://www.facebook.com/dachmt" target="_blank">Facebook</a> / <a href="https://www.twitter.com/dachmt" target="_blank">@dachmt</a>
    </p>
  </div>
</div>
{% endblock %}

webapp/templates/unsigned/contact.html
{% extends 'layouts/base_layout.html' %}
{% load staticfiles %}

{% block title %}Contact us - {{ site.name }}{% endblock %}

{% block javascripts %}
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCrS9olhNCDkvNXRw_M36yg9ON-dUDc0hs&sensor=false"></script>
<script type="text/javascript">
  function initialize() {
    var myQuiversLatlng = new google.maps.LatLng(37.766085,-122.424314);

    var mapOptions = {
      center: myQuiversLatlng,
      zoom: 15
    };

    var map = new google.maps.Map(
        document.getElementById("map-canvas"),
        mapOptions
    );

    var marker = new google.maps.Marker({
      position: myQuiversLatlng,
      map: map,
      title: 'MyQuivers'
    });
  }

  google.maps.event.addDomListener(window, 'load', initialize);
</script>
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <h1 class="page-header">Contact us</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-3">
    {% include "partials/unsigned_side_menu.html" with active='contact' %}
  </div>

  <div class="col-md-9">
    <div class="col-md-8">
    <form id="contact-form" class="form-horizontal" method="post" action="{% url 'contact' %}" role="form">
      <fieldset>
        {% csrf_token %}
        {% if form.non_field_errors %}
        <div class="alert alert-danger">{{ form.non_field_errors|striptags }}</div>
        {% endif %}
        {% if confirmation_message != None %}
        <div class="alert alert-success">{{ confirmation_message }}</div>
        {% endif %}

        <div class="form-group{% if form.sender.errors %} has-error{% endif %}">
          <label for="id_sender" class="col-md-2 control-label">Email</label>
          <div class="col-md-9">
            {{ form.sender }}
            {% if form.sender.errors %}
            <span class="help-block">{{ form.sender.errors|striptags }}</span>
            {% endif %}
          </div>
        </div>

        <div class="form-group{% if form.subject.errors %} has-error{% endif %}">
          <label for="id_subject" class="col-md-2 control-label">Subject</label>
          <div class="col-md-9">
            {{ form.subject }}
            {% if form.subject.errors %}
            <span class="help-block">{{ form.subject.errors|striptags }}</span>
            {% endif %}
          </div>
        </div>

        <div class="form-group{% if form.message.errors %} has-error{% endif %}">
          <label for="id_message" class="col-md-2 control-label">Message</label>
          <div class="col-md-9">
            {{ form.message }}
            {% if form.message.errors %}
            <span class="help-block">{{ form.message.errors|striptags }}</span>
            {% endif %}
          </div>
        </div>

        <div class="form-group">
          <div class="col-md-9 col-md-offset-2">
            <button type="submit" class="btn btn-primary">Send</button>
          </div>
        </div>
      </fieldset>
    </form>
  </div>
  <div class="col-md-3 col-md-offset-1">
      <address>
        <strong>MyQuivers.com</strong><br>
        312 Guerrero Street<br>
        San Francisco, CA 94103<br>
        <abbr title="Phone">P:</abbr> (408) 480-7497
      </address>

      <address>
        <strong>Email us</strong><br>
        <a href="mailto:contact@myquivers.com">contact@myquivers.com</a>
      </address>

      <div class="social-links">
        <a href="{{ facebook_url }}" target="_blank" data-toggle="tooltip" title="Facebook" data-placement="bottom">
          <img src="{% static 'images/icons/social/facebook.png' %}" alt="Facebook" class="small">
        </a>
        <a href="{{ twitter_url }}" target="_blank" data-toggle="tooltip" title="Twitter" data-placement="bottom">
          <img src="{% static 'images/icons/social/twitter.png' %}" alt="Twitter">
        </a>
        <a href="{{ instagram_url }}" target="_blank" data-toggle="tooltip" title="Instagram" data-placement="bottom">
          <img src="{% static 'images/icons/social/instagram.png' %}" alt="Instagram">
        </a>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div id="map-container" class="col-md-9 col-md-offset-3">
    <div id="map-canvas"></div>
  </div>
</div>
{% endblock %}

webapp/templates/unsigned/index.html
{% extends 'layouts/homepage_layout.html' %}
{% load staticfiles %}

{% block javascripts %}
  {% if debug %}
    <script src="{% static 'js/webapp/pages/unsigned/index.js' %}" xmlns="http://www.w3.org/1999/html"></script>
  {% endif %}
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-6">
    <img class="img-responsive logo" src="{% static 'images/logos/logo-inline-326x100-lightblue.png' %}">
  </div>
  <div class="col-md-6 text-right">
    <a href="{% url 'login' %}" class="btn btn-primary btn-sm">Log in</a>
  </div>
</div>
<div class="row">
  <div class="col-md-12 text-center">
    <h1>Your online surfboards rack</h1>
    <p class="lead">
      Keep track of what I had, what you have, and what you want.<br>
      Compare with others, find surfboard reviews and get your next board.<br>
      Go surf and stop wasting time.
    </p>
    <form id="registration-form-homepage" method="post" action="{% url 'register' %}" class="col-md-4 col-md-offset-4 col-sm-8 col-sm-offset-2">
      {% csrf_token %}
      {{ registration_form.email }}
      {{ registration_form.username }}
      {{ registration_form.password1 }}
      <button type="submit" class="btn btn-primary btn-large btn-block">Add your surfboards</button>
      <div class="small terms-agreed">
        By creating an account, your agree the <a href="{% url 'terms' %}">terms of service</a>.
      </div>
    </form>
  </div>
</div>
{% endblock %}

webapp/templates/unsigned/privacy.html
{% extends 'layouts/base_layout.html' %}
{% load staticfiles %}

{% block title %}Privacy policy - {{ site.name }}{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <h1 class="page-header">Privacy policy</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-3">
    {% include "partials/unsigned_side_menu.html" with active='privacy' %}
  </div>

  <div class="col-md-9 sections">
    <p>
      This Privacy Policy governs the manner in which MyQuivers collects, uses, maintains and discloses information
      collected from users (each, a "User") of the <a href="{% url 'index' %}">{{ site }}</a>
      website ("Site"). This privacy policy applies to the Site and all products and services offered by MyQuivers.
    </p>

    <section id="personal-identification-info">Personal identification information</section>
    <p>
      We may collect personal identification information from Users in a variety of ways, including, but not limited
      to, when Users visit our site, register on the site, fill out a form, and in connection with other activities,
      services, features or resources we make available on our Site. Users may be asked for, as appropriate, name,
      email address. We will collect personal identification information from Users only if they voluntarily submit
      such information to us. Users can always refuse to supply personally identification information, except that
      it may prevent them from engaging in certain Site related activities.
    </p>

    <section id="non-personal-identification-info">Non-personal identification information</section>
    <p>
      We may collect non-personal identification information about Users whenever they interact with our Site.
      Non-personal identification information may include the browser name, the type of computer and technical
      information about Users means of connection to our Site, such as the operating system and the Internet service
      providers utilized and other similar information.
    </p>

    <section id="web-browser-cookies">Web browser cookies</section>
    <p>
      Our Site may use "cookies" to enhance User experience. User's web browser places cookies on their hard drive
      for record-keeping purposes and sometimes to track information about them. User may choose to set their web
      browser to refuse cookies, or to alert you when cookies are being sent. If they do so, note that some parts of
      the Site may not function properly.
    </p>

    <section id="how-we-use-collected-info">How we use collected information</section>
    <p>
      MyQuivers may collect and use Users personal information for the following purposes:
      <ul>
        <li>
          <i>To personalize user experience</i>
          <p>We may use information in the aggregate to understand how our Users as a group use the services and resources provided on our Site.</p>
        </li>
        <li>
          <i>To improve our Site</i>
          <p>We may use feedback you provide to improve our products and services.</p>
        </li>
        <li>
          <i>To send periodic emails</i>
          <p>We may use the email address to respond to their inquiries, questions, and/or other requests. If User decides to opt-in to our mailing list, they will receive emails that may include company news, updates, related product or service information, etc. If at any time the User would like to unsubscribe from receiving future emails, they may do so by contacting us via our Site.</p>
        </li>
      </ul>
    </p>

    <section id="how-we-protect-your-info">How we protect your information</section>
    <p>
      We adopt appropriate data collection, storage and processing practices and security measures to protect
      against unauthorized access, alteration, disclosure or destruction of your personal information, username,
      password, transaction information and data stored on our Site.
    </p>

    <section id="sharing-your-personal-info">Sharing your personal information</section>
    <p>
      We do not sell, trade, or rent Users personal identification information to others. We may share generic
      aggregated demographic information not linked to any personal identification information regarding visitors
      and users with our business partners, trusted affiliates and advertisers for the purposes outlined above.
    </p>

    <section id="third-party-websites">Third party websites</section>
    <p>
      Users may find advertising or other content on our Site that link to the sites and services of our partners,
      suppliers, advertisers, sponsors, licensors and other third parties. We do not control the content or links
      that appear on these sites and are not responsible for the practices employed by websites linked to or from
      our Site. In addition, these sites or services, including their content and links, may be constantly changing.
      These sites and services may have their own privacy policies and customer service policies. Browsing and
      interaction on any other website, including websites which have a link to our Site, is subject to that
      website's own terms and policies.
    </p>

    <section id="changes-to-this-privacy-policy">Changes to this privacy policy</section>
    <p>
      MyQuivers has the discretion to update this privacy policy at any time. When we do, we will send you an email.
      We encourage Users to frequently check this page for any changes to stay informed about how we are helping to
      protect the personal information we collect. You acknowledge and agree that it is your responsibility to review
      this privacy policy periodically and become aware of modifications.
    </p>

    <section id="your-acceptance-of-these-terms">Your acceptance of these terms</section>
    <p>By using this Site, you signify your acceptance of this policy and
      <a href="{% url 'terms' %}">terms of service</a>. If you do not agree to this policy,
      please do not use our Site. Your continued use of the Site following the posting of changes to this policy
      will be deemed your acceptance of those changes.
    </p>

    <section id="contacting-us">Contacting us</section>
    <p>
      If you have any questions about this Privacy Policy, the practices of this site, or your dealings
      with this site, <a href="{% url 'contact' %}">contact us</a>.
    </p>

    <p class="text-muted small">This document was last updated on January 11, 2014</p>
  </div>
</div>
{% endblock %}